#!/usr/bin/env python3
"""Sources the Xbox build (tools/xbox_build.py) takes from the Linux port's.

    xbox_sources.py common port/linux/src/halo_linker_common.c OUT
        The pooled COMMON globals (every HALO_COMMON line), as plain zeroed
        definitions: the Xbox link has no weak symbols to fall back on, and
        nothing else defines them.
    xbox_sources.py bink port/linux/src/bink_null.c OUT
        The Bink stub, with the SDK's headers in place of the Linux
        platform layer's.
"""

import argparse
import re
from pathlib import Path

# what the stub uses of the Linux platform layer
PLATFORM = """#include <xtl.h>

ULONG __cdecl DbgPrint(PCSTR format, ...);
#define platform_log(format, ...) DbgPrint(format "\\n", ##__VA_ARGS__)"""

HEADER = "/* generated by tools/xbox_sources.py from {source}; do not edit */\n\n"


def common(source: Path) -> str:
    lines = [line for line in source.read_text(encoding="utf-8").splitlines()
             if re.match(r"HALO_COMMON\(\w+, *\d+\);", line)]
    if not lines:
        raise SystemExit(f"{source}: no HALO_COMMON definitions")
    return (HEADER.format(source=source.as_posix())
            + "#define HALO_COMMON(name, size) __declspec(align(16)) unsigned char name[size]\n\n"
            + "\n".join(lines) + "\n")


def bink(source: Path) -> str:
    text = source.read_text(encoding="utf-8")
    if '#include "platform.h"' not in text:
        raise SystemExit(f"{source}: its platform.h include moved")
    return HEADER.format(source=source.as_posix()) + text.replace('#include "platform.h"', PLATFORM)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("kind", choices=("common", "bink"))
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    text = common(args.source) if args.kind == "common" else bink(args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.is_file() or args.output.read_text(encoding="utf-8") != text:
        args.output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
